### ISSUE TITLE
Set cursor focus to main page search input element

### ISSUE THREAD

**Issue by RobBelics** [FreshPorts/freshports#147]
Right now, going to the main index page requires one to use the mouse or keyboard to set the cursor to the search input element to search for anything. Adding "autofocus" to that input element will automatically set the cursor there without the user having to do that.

Similar to what already happens here but with the search elements in the top center: https://www.freshports.org/search.php

**Comment by dlangille** [comment]
How is https://dev.freshports.org ?

We could do this for every page.

**Comment by dlangille** [comment]
@RobBelics how's that look now?

**Comment by RobBelics** [comment]
I don't see any change at all.

**Comment by dlangille** [comment]
@RobBelics dev? are you checking  https://dev.freshports.org ?

**Comment by RobBelics** [comment]
Oops! Sorry. Yes, that's exactly what I'm looking for.

**Comment by dlangille** [comment]
Now in production.

**Comment by swills** [comment]
This made it so that hitting space to scroll down after going to the home page doesn't work.

**Comment by dlangille** [comment]
I may make this a user preference.  Default to no focus, if logged in, sets focus if you want it to.

**Comment by RobBelics** [comment]
Just use Page Down instead of the spacebar. Problem solved.
I would think people are more likely to come to the site searching for
something than wanting to scroll through recent commits which change
continuously.

**Comment by swills** [comment]
> Just use Page Down instead of the spacebar. Problem solved. 

I could just as easily say: Just click the search box if you want to search. Problem solved. I would think people expect this site to be have like so many other sites, where hitting space bar scrolls down and if you want to search, you click the search box. GitHub for example has a search box which is not focused by default and you can easily scroll through commits which change or other things.

To me, it seems a matter of perspective or personal preference. So I think having it as a user preference when logged in makes sense.

**Comment by dlangille** [comment]
```
ALTER TABLE public.users
    ADD COLUMN set_focus_search boolean NOT NULL DEFAULT False;

COMMENT ON COLUMN public.users.set_focus_search
    IS 'When there is a search field on the page, set the focus to that field when the page is loaded.';
```

**Comment by dlangille** [comment]
@swills  & @RobBelics - a fix is now installed at https://dev.freshports.org/ - At least for a little while until I swap branches to work on something else.

* the behaviour is now reverted to the original actions before this issue was worked on

* If you want to set the focus to the search box, check the `Set focus to search box` box at https://dev.freshports.org/customize.php

* this setting has no effect at https://dev.freshports.org/search.php
* focus has always been set to search box at https://dev.freshports.org/search.php
* I have considered not setting focus when viewing search results - that allows the space bar to invoke page down - no action taken yet.

**Comment by dlangille** [comment]
This is now in production.
