### ISSUE TITLE
Add dark mode to freshports?

### ISSUE THREAD

**Issue by kraileth** [FreshPorts/freshports#304]
Adding a dark mode either for logged in users or selectable on the main page could be nice for people who either prefer it in general or work on ports at night.

(This originated from a [reddit post](https://www.reddit.com/r/freebsd/comments/o0650z/why_is_freshports_trying_so_hard_to_look_as_ugly/) mine obviously written in a bad mood and ignorant to a specific detail of US culture. But still maybe something useful comes out of it.)

**Comment by jethron** [comment]
Knocked up a _very_ rough first pass up on https://a.freshports.org/

This uses the built-in dark mode preference support in CSS. So it uses the preference set in the browser or operating system settings. You can usually toggle this in the browser Developer Tools too, if you don't want to toggle the entire browser setting just to test this.

Note at the moment that environment also includes some changes to the Pride Month decoration, to be a bit less intense and more flag-like. 

Any feedback on either change is much appreciated @kraileth! Your feedback is useful, even if it isn't from a great mood. :D

**Comment by dlangille** [comment]
@kraileth what do you think?

**Comment by kraileth** [comment]
Sorry, was off for a couple of days.

@jethron Reduced decoration works well for me - in fact I think now that it doesn't repeat, it's actually better recognizable as rainbow colors (at least for me the previous one was overwhelming). Other than that the page looks like it always does for me, though, even though I set Firefox to use the dark theme. Did a little reading and it seems that the two things are not related. After enabling `devtools.inspector.color-scheme-simulation.enabled`, I was able to switch to dark mode using the dev tools. It looks pretty neat. Thanks for your work!

Now I only need to figure out how to enable this setting system-wide on FreeBSD (or at least browser-wide on FF and Chromium). :smiley:

**Comment by jethron** [comment]
Thanks @kraileth! PR opened. I think it depends on your desktop environment; using a dark theme in your window manager is usually enough to trigger the GTK setting I believe Firefox adheres to.

But otherwise you should be able to force it browser-wide via:
- For Firefox: head to [`about:config`](about:config) and add an integer preference for `ui.systemUsesDarkTheme`; you can set this to 1 to force-enable it, and 0 to force-disable
- For Chrome: Try [`chrome://flags/` and search for "Force Dark Mode"](chrome://flags/#enable-force-dark)

There are also [Extensions](https://addons.mozilla.org/en-US/firefox/addon/dark-mode-website-switcher/) for toggling the feature.

**Comment by dlangille** [comment]
This is now in production.

**Comment by dlangille** [comment]
@jethron feedback from IRC:

One person said:

* it would also be fine to extend it to the whole page, as long as it doesn't change as you scroll
* it was mostly the fact that the colors kept changing when i would scroll really rapidly that would distract me a lot

**Comment by dlangille** [comment]
> Note at the moment that environment also includes some changes to the Pride Month decoration, to be a bit less intense and more flag-like.

This just appeared on my screen today, for the first time this year. I'd forgotten about it.
