### ISSUE TITLE
Support apostrophe ' in searches

### ISSUE THREAD

**Issue by grahamperrin** [FreshPorts/freshports#358]
Results for _Encrypt client_ <https://www.freshports.org/search.php?stype=shortdescription&method=match&query=Encrypt+client&search=Search> include: 

> **lego** Let's Encrypt client and ACME library written in Go

> **py-certbot** Let's Encrypt client

### Bug

Seeking _Let's Encrypt_ <https://www.freshports.org/search.php?stype=shortdescription&method=match&query=Let%27s+Encrypt&num=10&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head>: 

* finds nothing
* presents _Let''s Encrypt_ (two apostrophes) in the search field

If the duplication is not noticed, then altering the search from Short Description to Long Description finds nothing, and: 

* presents _Let''''s Encrypt_ (four apostrophes) …

**Comment by dlangille** [comment]
The first problem I see is the escaping of special characters occurs too early. See https://github.com/FreshPorts/freshports/blob/master/www/search.php#L192

What we should be doing there is capturing the raw data we are given. `pg_escape_string` should be used when using the value a database query. `htmlentities` should be used when displaying the same data.

**Comment by dlangille** [comment]
The problem was the early use of `pg_escape_string`

Try the same query on dev: 

https://dev.freshports.org/search.php?stype=shortdescription&method=match&query=Let%27s+Encrypt&num=10&orderby=category&orderbyupdown=asc&search=Search&format=html&branch=head

You'll notice that `dev` no longers adds extra quotes to the search criteria.  `www` still does. That was the issue.

While here, verify that whenever `$query` is used:

* output: `htmlentities()`
* database query: `pg_escape_string()`

**Comment by grahamperrin** [comment]
Sweet.
